added comments to lint workflow

diff --git a/.github/workflows/backend-CI.yml b/.github/workflows/backend-CI.yml
--- a/.github/workflows/backend-CI.yml
+++ b/.github/workflows/backend-CI.yml
@@ -31,18 +31,27 @@ jobs:
         id: lint
         continue-on-error: true
         run: |
-          npx standard --env=jest Backend/
+          set +e  # disable immediate exit on error
+          OUTPUT="$(npx standard --env=jest Backend/ 2>&1)"
+          EXIT_CODE=$?
+          echo 'lint_output<<EOF' >> $GITHUB_OUTPUT
+          echo "$OUTPUT" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
 
       - name : Create comment
-        if: steps.lint.outcome == 'failure'
+        if: steps.lint.outputs.exit_code != '0'
         uses: mshick/add-pr-comment@v2
         with:
           message: |
             **There is one or more linting errors**
+            ```
+            ${{ steps.lint.outputs.lint_output }}
+            ```
             🌏
 
       - name: Push changed code if lint fails
-        if: steps.lint.outcome == 'failure'
+        if: steps.lint.outputs.exit_code != '0'
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
