Fixed remaining lint issues.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -85,15 +85,11 @@ jobs:
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-          git add .
-          if git diff --cached --quiet; then
-            echo "No changes to commit"
-          else
-            git commit -m "Fixed some lint errors"
-            git push
-            echo "Exiting workflow due to remaining lint errors"
-            exit 1
-          fi
+          git add .    
+          git commit -m "Fixed some lint errors"
+          git push
+          echo "Exiting workflow due to remaining lint errors"
+          exit 1
 
       - name: Format backend using prettier
         run: |
